baseurl: https://velvety-pithivier-152e8b.netlify.app
DefaultContentLanguage: en
title: Antoni Sieminski
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/antoni_linkedin.jpeg
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: no
  showRelatedPosts: yes
  socialShare: yes
  subtitle: Advanced regression methods for corporate data scientists
  useHLJS: yes
  wordCount: no
Author:
  email: a.m.sieminski@gmail.com
  github: asieminski
  linkedin: antonisieminski
menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - identifier: consulting
      name: Consulting
      weight: 2
    - name: Oversight
      parent: consulting
      url: post/2017-03-07-bigimg-sample
      weight: 1
    - name: Execution
      parent: consulting
      url: post/2017-03-05-math-sample
      weight: 2
    - name: Training (in development)
      parent: consulting
      url: post/2016-03-08-code-sample
      weight: 3
    - name: Portfolio
      url: page/portfolio/
      weight: 3
    - name: Tags
      url: tags
      weight: 3
